# Generated by Django 4.2.7 on 2025-12-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="is_verified",
            field=models.BooleanField(default=True),
        ),
    ]
