# Generated by Django 4.2.7 on 2025-12-09 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "location",
                    models.CharField(
                        help_text="Address or location name", max_length=200
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "size_hectares",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("soil_type", models.CharField(blank=True, max_length=100)),
                (
                    "main_crops",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of main crops grown on this farm",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farms",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "farms",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["owner"], name="farms_owner_i_f0af72_idx"),
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="farms_latitud_ab4052_idx",
                    ),
                ],
            },
        ),
    ]
