# Generated by Django 4.2.7 on 2025-12-09 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CropImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="crop_images/")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional notes about the crop condition"
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crop_images",
                        to="farms.farm",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submitted_diagnoses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "crop_images",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DiagnosisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "predicted_label",
                    models.CharField(
                        help_text="Predicted disease or issue", max_length=200
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(help_text="Confidence score (0.0 to 1.0)"),
                ),
                (
                    "recommendations",
                    models.JSONField(
                        default=dict,
                        help_text="Structured recommendations including treatment, products, etc.",
                    ),
                ),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model_version",
                    models.CharField(
                        default="v1.0", help_text="ML model version used", max_length=50
                    ),
                ),
                (
                    "crop_image",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnosis_result",
                        to="diagnosis.cropimage",
                    ),
                ),
            ],
            options={
                "db_table": "diagnosis_results",
                "ordering": ["-processed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="cropimage",
            index=models.Index(
                fields=["submitted_by"], name="crop_images_submitt_e1f6ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cropimage",
            index=models.Index(fields=["status"], name="crop_images_status_da96ed_idx"),
        ),
        migrations.AddIndex(
            model_name="cropimage",
            index=models.Index(
                fields=["timestamp"], name="crop_images_timesta_c42f40_idx"
            ),
        ),
    ]
