# Generated by Django 4.2.7 on 2025-12-09 17:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mpesa_transaction_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="M-Pesa transaction ID (e.g., QLXXXXX)",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "checkout_request_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="M-Pesa checkout request ID",
                        max_length=100,
                        null=True,
                        unique=True,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "phone",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be in format +2547XXXXXXXX or +2541XXXXXXXX",
                                regex="^\\+254[17]\\d{8}$",
                            )
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="initiated",
                        max_length=20,
                    ),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        default=dict, help_text="Raw response from M-Pesa API"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Error message if transaction failed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="marketplace.order",
                    ),
                ),
            ],
            options={
                "db_table": "transactions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["mpesa_transaction_id"],
                        name="transaction_mpesa_t_23bed8_idx",
                    ),
                    models.Index(
                        fields=["checkout_request_id"],
                        name="transaction_checkou_25a10d_idx",
                    ),
                    models.Index(
                        fields=["status"], name="transaction_status_505a2f_idx"
                    ),
                    models.Index(
                        fields=["order"], name="transaction_order_i_c4ecd3_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="transaction_created_5c02ac_idx"
                    ),
                ],
            },
        ),
    ]
